### ISSUE TITLE
Pour speling

### ISSUE THREAD

**Issue by Wynndow** [alphagov/digitalmarketplace-runner#20]

**Comment by samuelhwilliams** [comment]
Please feel free to raise a PR to assert your mastery of the English language. 👍

**Comment by samuelhwilliams** [comment]
Gonna close this down as I doubt either of us can remember the spelling in question.

More details next time please! 🙈

**Comment by Wynndow** [comment]
Hah. Fair do's. I'm pretty sure you fixed it up anyway.

I'm thinking about stealing this runner for Verify at some point btw, if you don't mind...

**Comment by samuelhwilliams** [comment]
Hopefully it shouldn't be too hard to port across :) Editing `config/settings.yml` _should_ allow you to run fairly arbitrary things.

If you do try, please let me know. Would love if it could be adapted to other uses!

**Comment by samuelhwilliams** [comment]
Although I'd probably be surprised to hear Verify doesn't have some alternative already?

**Comment by Wynndow** [comment]
At the moment it's just  a startup script which brings apps up and drops them to the background, with logs piped into files. You need to tail the files if you want to see what's going on, and it's hard to see what's running/restart an app etc.

**Comment by Wynndow** [comment]
Will let you know if I get round to use it!

**Comment by samuelhwilliams** [comment]
Oh yeah that feels like that would get annoying. Nice one. Cheers!
