### ISSUE TITLE
Error 11!

### ISSUE THREAD

**Issue by benvand** [alphagov/digitalmarketplace-runner#26]
**Describe the bug**
Looks like the make setup bails if it can't find docker. Is there a way to make the error message nicer?

**To Reproduce**
1. Kill docker
2. `make setup`
3. Experience sadness

**Expected behavior**
A clear and concise error message telling me that docker isn't available and that I need to run it

**Screenshots**
![screen shot 2018-07-06 at 09 46 35](https://user-images.githubusercontent.com/3469840/42369325-83c89a0c-8101-11e8-8ee8-b71f41861350.png)

**Comment by benvand** [comment]
I got this when I tried to start docker

<img width="673" alt="screen shot 2018-07-06 at 09 48 30" src="https://user-images.githubusercontent.com/3469840/42369408-c9fda576-8101-11e8-98fe-4fcfc9e9d392.png">

**Comment by benvand** [comment]
Nice error for node though 👍 

![screen shot 2018-07-06 at 09 49 33](https://user-images.githubusercontent.com/3469840/42369455-ef5fdb90-8101-11e8-90e4-25853b0e6fec.png)

**Comment by samuelhwilliams** [comment]
https://github.com/alphagov/digitalmarketplace-runner/pull/29

**Comment by samuelhwilliams** [comment]
Fixed by PR https://github.com/alphagov/digitalmarketplace-runner/pull/29
