### ISSUE TITLE
Tell people how to install the correct node version?

### ISSUE THREAD

**Issue by benvand** [alphagov/digitalmarketplace-runner#27]
**Is your feature request related to a problem? Please describe.**
I couldn't figure out how to install the specified node version so I just changed the `SPECIFIC_NODE_VERSION` variable.

**Describe the solution you'd like**
Maybe tell people how to do it?

**Describe alternatives you've considered**
We could have a min version or a range. I think any v6 would probably be fine?

**Comment by katstevens** [comment]
Yeah, I changed the node version in `setup.py` to my local version (`v6.14.3`) and everything seems fine.

**Comment by jonodrew** [comment]
This is fixed with #43
