### ISSUE TITLE
Allow multiple search indexes in `settings.yml`

### ISSUE THREAD

**Issue by lfdebrux** [alphagov/digitalmarketplace-runner#34]
**Is your feature request related to a problem? Please describe.**
I'm playing around with direct award projects, and in the datasets available they are almost entirely G-Cloud 9. However, since the release of G-Cloud 10, I can't use these projects, as I ran `make data` and lost the search indices for 9. I don't want to put my local system back into 10 though.

**Describe the solution you'd like**
Ideally I would be able to specify that both 9 and 10 would be indexed. I think that can be done using the search-api, but it would be neat if I just changed `settings.yml`, ran `make data`, and let dmrunner magically take care of it for me ;)

**Describe alternatives you've considered**
Changing `settings.yml` search settings to G-Cloud 9, running `make data`, and hoping it doesn't delete the old indices.

**Additional context**
I am using the latest cleaned data set and a beta version of dmrunner with `make data` (#32)

**Comment by samuelhwilliams** [comment]
See comment here: https://github.com/alphagov/digitalmarketplace-runner/pull/32#issuecomment-404139831

While I can't test this here and now, I'm confident this is already possible as it's a reality I considered when creating the setup process. So I feel fairly confident that we can close this off for now.

**Comment by lfdebrux** [comment]
That did indeed work. Sorry for not checking first!

**Comment by samuelhwilliams** [comment]
:+1:

If g9 index is something that probably shouldn't haven't been removed from settings in the first place, might be worth updating it so that direct award stuff keeps working for anyone else who may use DM runner stuff.
